name: Stage the app

env:
  DOCKER_IMAGE_NAME: docmilo-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: docmilo-ttt-app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    runs-on: ubuntu-lateststeps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
         npm install
         npm run build
      - uses: actions/upload-artifact@v2
      with:
       name: webpack artifacts
       path: public/
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    name: Deploy app container to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: leslwingbast
          password: ${{ secrets.GITHUB_TOKEN }}}
      - name: Deploy web app container
    uses: azure/webapps-deploy@v2
        with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        images: ${{env.IMAGE_REGISTRY_URL}}/leslwing//L00177784_CA2_GolfApp/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
      - name: Azure logout
        run: |
         az logout
