name: Stage the app

env:
  DOCKER_IMAGE_NAME: l00177784_ca2_golfapp
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_WEBAPP_NAME: leslwingbast-golfapp
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  pull_request:
    types: [labeled]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  Build-Imgage-and-Publish:
    needs: Build 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/leslwingbast/l00177784_ca2_golfapp          
          labels: ${{ steps.meta.outputs.labels }}
  
  # deploy app to azure production environemnt
  Deploy-to-Azure:
    needs: Build-Imgage-and-Publish
    if: contains(github.event.pull_request.labels.*.name, 'production')
    runs-on: ubuntu-latest
    
    name: Deploy app container to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: leslwingbast
          password: ${{ secrets.MYTOKEN }}
      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/leslwingbast/${{env.DOCKER_IMAGE_NAME}}
      - name: Azure logout
        run: |
         az logout
